<?php

$countries = [
    "AFG" => "Afghanistan",
    "ALB" => "Albania",
    "DZA" => "Algeria",
    "AND" => "Andorra",
    "AGO" => "Angola",
    "ARG" => "Argentina",
    "ARM" => "Armenia",
    "AUS" => "Australia",
    "AUT" => "Austria",
    "BHR" => "Bahrain",
    "BGD" => "Bangladesh",
    "BEL" => "Belgium",
    "BRA" => "Brazil",
    "CAN" => "Canada",
    "CHN" => "China",
    "COL" => "Colombia",
    "DNK" => "Denmark",
    "EGY" => "Egypt",
    "FIN" => "Finland",
    "FRA" => "France",
    "DEU" => "Germany",
    "GRC" => "Greece",
    "IND" => "India",
    "IDN" => "Indonesia",
    "IRL" => "Ireland",
    "ITA" => "Italy",
    "JPN" => "Japan",
    "JOR" => "Jordan",
    "KWT" => "Kuwait",
    "LBN" => "Lebanon",
    "MYS" => "Malaysia",
    "MEX" => "Mexico",
    "MAR" => "Morocco",
    "NLD" => "Netherlands",
    "NZL" => "New Zealand",
    "NOR" => "Norway",
    "OMN" => "Oman",
    "PAK" => "Pakistan",
    "PRT" => "Portugal",
    "QAT" => "Qatar",
    "SAU" => "Saudi Arabia",
    "SGP" => "Singapore",
    "ZAF" => "South Africa",
    "ESP" => "Spain",
    "SWE" => "Sweden",
    "CHE" => "Switzerland",
    "TUR" => "Turkey",
    "ARE" => "United Arab Emirates",
    "GBR" => "United Kingdom",
    "USA" => "United States"
];

$nationalities = [
    "Afghan",
    "Albanian",
    "Algerian",
    "Andorran",
    "Angolan",
    "Argentine",
    "Armenian",
    "Australian",
    "Austrian",
    "Bahraini",
    "Bangladeshi",
    "Belgian",
    "Brazilian",
    "Canadian",
    "Chinese",
    "Colombian",
    "Danish",
    "Egyptian",
    "Finnish",
    "French",
    "German",
    "Greek",
    "Indian",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Jordanian",
    "Kuwaiti",
    "Lebanese",
    "Malaysian",
    "Mexican",
    "Moroccan",
    "Dutch",
    "New Zealander",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Portuguese",
    "Saudi",
    "Singaporean",
    "South African",
    "Spanish",
    "Swedish",
    "Swiss",
    "Turkish",
    "Emirati",
    "British",
    "American"
];